### ISSUE TITLE
homebridge-sense 0.2.0 - TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by URBANsUNITED** [luc-ass/homebridge-sense#12]
Hi!

I've just installed homebridge-sense 0.2.0 to my homebridge setup, but it doesn't work.
This is the error i'll get:

[2018-1-19 18:43:30] Homebridge is running on port 51826.
/usr/local/lib/node_modules/homebridge-sense/lib/sense.js:10
			temperature_value = json.temperature.value;
			                                     ^

TypeError: Cannot read property 'value' of undefined
    at /usr/local/lib/node_modules/homebridge-sense/lib/sense.js:10:41
    at Request._callback (/usr/local/lib/node_modules/homebridge-sense/lib/sense.js:150:12)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-sense/node_modules/request/request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-sense/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-sense/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)

npm 5.6.0
node v9.3.0
homebridge@0.4.36

What could this be?

Thanks
URBANsUNITED

**Comment by luc-ass** [comment]
Hm, not really sure. Perhaps @kcharwood has an idea what this could be. Perhaps he could let you know which versions of npm/node/homebridge he's running.

**Comment by luc-ass** [comment]
Hm, now mine isn't working as well. I'll have to dive deeper into it. -

**Comment by URBANsUNITED** [comment]
Thanks for letting me know! Let's call it some kind of progress... Even it's a sh*t situation for you. 
Thanks in advance.

**Comment by luc-ass** [comment]
You have probably heard that hello.IS is shutting down its operations. As of now I cannot connect to my sense device via their own app so it is probably not a fault on our plugin side, more likely that it’s a problem of the server operations.

Let me know whether you are able to connect to their server/your data via the Sense app.

**Comment by URBANsUNITED** [comment]
Realy? No I haven't heard off. Oh it's a shame. I like the devices.
My app on the iPhone works without any issues even outside my wifi area.

**Comment by MrTeal** [comment]
@URBANsUNITED your app still works? mine is stating: "There was a problem displaying your sensor data. please try again." on about every screen :(

**Comment by gcordalis** [comment]
Looks like something has happened to their servers... Their website is offline with an error `(Service Unavailable: Back-end server is at capacity)` which seems odd. 

I'm thinking this is the end of sense :(

**Comment by MrTeal** [comment]
that's too bad :( 
Hopefully this project takes off so we can still use the hardware:
https://github.com/0ff/long-live-sense

**Comment by URBANsUNITED** [comment]
Sorry, for the maybe misunderstanding from my side.
I am using the sen.se thermopeanuts which I wanted to interact with homekit/homebridge. 
They work without any issues in my network and app. 
You use the mother, right?

**Comment by luc-ass** [comment]
This is a totally different device. It has nothin to do with the Hello Sense Sleep tracker this plugin is for.

**Comment by gcordalis** [comment]
@MrTeal Sadly that project hasn't had anything done since the announcement. I think we're sweet out of luck with sense. Time to find a replacement.

**Comment by gcordalis** [comment]
Looks like they’ve released their source code: https://github.com/hello

**Comment by MrTeal** [comment]
ah nice! so there's hope now :-) 
i'm no programmer so I kinda depend on the community here..

**Comment by luc-ass** [comment]
Well, the question is wether the device can be accessed locally... would be great!

**Comment by MrTeal** [comment]
Indeed! so we can upgrade it to make it look at your own server instead of Sense's server.

**Comment by gcordalis** [comment]
Reading through all their code now. If I find anything useful I’ll let you know :)

**Comment by MrTeal** [comment]
Thanks alot! :D

**Comment by rchatham** [comment]
Any progress finding out how to get your own instance of the Sense server running?

**Comment by gcordalis** [comment]
Hit a road block - running the server is the 'easy' part.
Getting the sense to speak to the custom server is where it gets very tricky. Unlikely that anything will come of it unless someone can take control of the Hello domain.

**Comment by luc-ass** [comment]
I will have to look into the config of my switch and firewall wether I can reroute traffic ...

**Comment by luc-ass** [comment]
Perhaps something like plexconnect would work

**Comment by gcordalis** [comment]
Last I checked traffic is over SSL so the server end will need a valid cert for the Hello domain.

I'd thought about changing DNS as well but sadly I don't think it'll do the trick.
