### ISSUE TITLE
JSON is empty when Homebridge has no internet-connectivity

### ISSUE THREAD

**Issue by gismo141** [luc-ass/homebridge-sense#3]
```Bash
/usr/local/lib/node_modules/homebridge-sense/lib/sense.js:95
		var json = JSON.parse(res.body);
		                         ^

TypeError: Cannot read property 'body' of undefined
    at Request._callback (/usr/local/lib/node_modules/homebridge-sense/lib/sense.js:95:28)
    at self.callback (/usr/local/lib/node_modules/homebridge-sense/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-sense/node_modules/request/request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
```

**Comment by luc-ass** [comment]
#4 thanks!

**Comment by gismo141** [comment]
Yeah normal people have an internet connection when using homebridge :)

But while waiting for the Telekom, I was developing and found out about this "problem" ;)
