### ISSUE TITLE
Error on homebridge 0.4.10

### ISSUE THREAD

**Issue by lnlyssg** [luc-ass/homebridge-sense#5]
I just updated to homebridge 0.4.10 and also updated this plugin but on trying to start homebridge up again I am now getting the error below:

```
/usr/lib/node_modules/homebridge-sense/index.js:102
        .on('get', this.getParticulateDensity.bind(this));
        ^

TypeError: Cannot read property 'on' of undefined
    at Object.getServices (/usr/lib/node_modules/homebridge-sense/index.js:102:9)
    at Server._createAccessory (/usr/lib/node_modules/homebridge/lib/server.js:378:36)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:266:26)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

```

**Comment by luc-ass** [comment]
Hm, I have not updated to the latest version yet. It Looks like `airQualityService` is not created... perhaps something changed in HAPnodeJS? I'll look into it.
Does this error persist or occur with any other platform? It is quite a basic funtion... Do you use other accessories?

**Comment by lnlyssg** [comment]
I have the homebridge-netatmo plugin up and running and that appears to be giving air quality information OK....

**Comment by soffes** [comment]
I'm also seeing this issue on homebridge 0.4.16

```
[Sense] Initializing Sense accessory...
/usr/lib/node_modules/homebridge-sense/index.js:102
        .on('get', this.getParticulateDensity.bind(this));
        ^

TypeError: Cannot read property 'on' of undefined
    at Object.getServices (/usr/lib/node_modules/homebridge-sense/index.js:102:9)
    at Server._createAccessory (/usr/lib/node_modules/homebridge/lib/server.js:378:36)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:266:26)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by luc-ass** [comment]
updated npmjs
thank you very much for fixing this bug!
